[package]
name = "day07"
version = "0.1.0"
authors = ["thorstel <thorstel@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path="../intcode" }
permutohedron = "0.2.4"
